config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'categories#index'

    
    

    resources :categories 
    resources :items

end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true
    has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
    validates :title, presence: true
    validates :price, presence: true
    validates :description, presence: true, length: {maximum: 500}
    validates :category_id, presence: true
    validates :email, presence: true
    has_many :item_images, dependent: :destroy
    accepts_nested_attributes_for :item_images
    belongs_to :category
    
     def self.search(searchq)
        if searchq
            where('title LIKE ?',"%#{searchq}%") 
        else
           all
        end
     end
end

app/models/item_image.rb
class ItemImage < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
    belongs_to :item
    validates :item_id, presence: true
    validates :picture, presence: true
    #validate :picture_size
    
    def picture_size
        if picture.size > 5.megabytes
            errors.add(:picture, "image size can't be greater than 5MB")
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    helper_method :sort_param, :sort_direction
    
    def index
        @items = Item.order('created_at DESC').limit(12)
    end
    
    def show
        @cat_id = params[:id]
       # @cat_name = Category.find_by_name(category_id: @cat_id)
        @items = Item.where(category_id: @cat_id).paginate(:per_page => 30,page: params[:page])
    end
    
    private
    def sort_param
        (["title","price"].include?(params[:sort]))? params[:sort] : "price"
    end
    
    def sort_direction
       direction =  (%w[asc desc].include?(params[:dir]))? params[:dir] : "asc"
    end
end

app/controllers/item_images_controller.rb
class ItemImagesController < ApplicationController
    def create
        
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    helper_method :sort_param, :sort_direction
    before_filter :authenticate_user!, :except => [:show,:index]
    
    def new
        @item = Item.new
        @item.item_images.build if @item.item_images.nil?
        
    end
    
    def create
        @item = Item.new(item_params)
        if @item.save
            if params[:item_images]
                 params[:item_images]['picture'].each do |i|
                 @item.item_images.create!(:picture => i, :item_id => @item.id)
            end
        end
            redirect_to items_path
        else
            render 'new'
        end
    end
    
    def show
        @item = Item.find_by(id: params[:id])
    end
    
    def destroy
        Item.find_by(params[:id]).destroy
        flash[:success] = "Item Destroyed"
        redirect_to items_path
    end
    
    def index
      
         @items = Item.search(params[:search]).order(sort_param + " " + sort_direction).paginate(:per_page => 10, page: params[:page])
         @categories = Category.all
    end
    
    def edit
    end
    
    def update
    end
    
    def item_params
        params.require(:item).permit(:title, :price, :description, :email, :category_id)
    end
    
    private
    def sort_param
        (["title","price"].include?(params[:sort]))? params[:sort] : "price"
    end
    
    def sort_direction
       direction =  (%w[asc desc].include?(params[:dir]))? params[:dir] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        direction = (column == sort_param && sort_direction == "asc")? "desc" : "asc"
        link_to column.titleize, params.merge(:sort => column, :dir =>direction, :page => nil)
    end
    
    def catergory_list
        @categories = Category.all
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_images_helper.rb
module ItemImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_category.html.erb
<tr>
     <th><span><%= link_to category.name ,category_path(category.id) %></span></th>
      <th><span><%= link_to 'Delete', category, method: :delete, data: {confirm: "You Sure?"}, :class => 'btn btn-mini btn-danger' %></span></th>
</tr>

app/views/categories/index.html.erb
<% provide(:title,"All Categories") %>
<h1> Recently Added </h1>
<%= render 'shared/itemtable' %>
 
  

app/views/categories/show.html.erb
<% provide(:title,"Show Items")%>
<h1>Show Items</h1>
<%= will_paginate @items %>
<%= render 'shared/itemtable' %>
<%= will_paginate @items %>

app/views/items/_item.html.erb
<div class="thumbnail">
        <%= link_to image_tag(item.item_images.first.picture_url ,:class => 'img'), item_path(item) %>
        <div class="caption">
            <h3><%= item.title %></h3>
            Price: <span><%= item.price %></span>
            <p><a href="#" class="btn btn-primary" role="button">Add to Cart</a> 
            
        </div>
</div>









   

app/views/items/edit.html.erb
<h1>Inside Edit</h1>

app/views/items/index.html.erb
<% provide(:title,"All Items") %>
<h1> Item List </h1>
<%= will_paginate @items %>
<%= render 'shared/itemtable' %>
<%= will_paginate @items %>
   
  

app/views/items/new.html.erb
<% provide(:title,"New Item") %>
<h1>Add New Item</h1>
<div class= "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@item, :html => { :multipart => true }) do |f| %>
            <%= f.label :email, :autofocuse => true  %>
            <%= f.text_field :email, :required => true %>
   
            <%= f.label :title %>
            <%= f.text_field :title, :required => true %>
    
            <%= f.label :price%>
            <%= f.text_field :price , :required => true %>
    
            <%= f.label :description%>
            <%= f.text_area :description, :required => true %>
    
            <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true, :prompt => "Please select a Category"%>
    
            <%= f.fields_for :item_image do |p| %>
               <%= p.label :picture %>
               <%= p.file_field :picture, :multiple => true, name: "item_images[picture][]" , accept: 'image/jpeg,image/gif,image/png'%>
            <% end %>
           
              <%= f.submit "Add Item", class: "btn btn-primary"%>
          
       <% end %>
   </div>
 </div>
 <%= render 'shared/browse_cat'%>
 
 <script type = "text/javascript">
     $('#item_item_image_picture').bind('change',function() {
        size_mb = this.files[0].size/1024/1024;
        if (size_mb > 5) {
            alert("Image should be lesser than 5MB");
        }
         
     });
 </script>

   

app/views/items/show.html.erb
<%= render @item %>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
    <div class = "container">
      
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
      <nav>
        <ul class = "nav navbar-nav navbar-left">
          <li><%= render 'layouts/search' %></li>
          <li><%= link_to "Home", categories_path %></li>
          <li><%= link_to "Help", '#' %></li>
          <li><%= link_to "About", '#' %></li>
          <li><%= render 'shared/additem'%></li>
        </ul>
      </nav> 
    </div>
    
</header>

app/views/layouts/_search.html.erb
    <div class="col-lg-4">
    <%= form_tag items_path, :method => 'get', :class => 'input-group' do%>
        <%= hidden_field_tag :sort, params[:sort] %>
        <%= hidden_field_tag :dir, params[:dir] %>
        <%= text_field_tag :search, params[:search],:type =>'search',:class => 'form-control',:placeholder => 'Search' %>
        <span class="input-group-btn">
            <%= submit_tag "Search", :name => nil, :class => 'btn btn-default'%>
        </span>
    <% end %>
    </div>
  
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class = "container-fluid">
    <%= render 'layouts/header' %>
  
    <%= render "shared/sidebar", collection: catergory_list %>
  
  <div class = "container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_additem.html.erb
<div>
    <%= link_to 'Post An Item', new_item_path,:class => 'btn btn-primary'  %>
</div>

app/views/shared/_browse_cat.html.erb
</br>
<div>
    <span><%= link_to 'Browse Categories', categories_path,:class => 'btn btn-primary'%></span>
</div>

app/views/shared/_itemtable.html.erb
<div class = "col-md-9">
<% @items.in_groups_of(3, false).each do |group| %>
  <div class='row'>
    <% group.each do |item| %>
      <div class='col-lg-3 col-sm-4 col-xs-6'>
          <%= render item %>
      </div>
     <% end %>
    </div>
<% end %>
</div>
</br>
<div class = 'col-md-1'>
  
</div>

app/views/shared/_sidebar.html.erb
<div class="col-md-2 col-md-pull-1">
  <table class = "table">
    <thead>
      <tr>
        <th>Categories</th>
      </tr>
    </thead>
    <tbody>
     
    <% @categories.each do |e| %>
    
        <tr class = 'row'>
          <td><h4><%= link_to e.name, category_path(e.id) %></h4></td>
        </tr>
    <% end %>
    
    </tbody>
  </table>
</div>